[browser]
gatherUsageStats = false

[server]
headless = true
port = 8501

[theme]
primaryColor = "#005587"
backgroundColor = "#f7f9fb"
secondaryBackgroundColor = "#f0f4f8"
textColor = "#2f3438"
font = "sans serif"
